### ISSUE TITLE
Need help with my badge

### ISSUE THREAD

**Issue by marcosn250r** [jaku/DEFCON-32-BadgeFirmware#6]
Regardless of what firmware I use, my badge can't access the memory card with message: "Cannot find a valid FAT filesystem on the SD card"
I have formatted the SD card in FAT32 and tried several other cards. Same issue every time.

Can you help?

**Comment by joekir** [comment]
Same issues for me, if there's details on what format it must be in that will help!

**Comment by jaku** [comment]
Try to format as fat32 and create a ROM and SAVE folder on the sdcard.
